kind: Deployment
apiVersion: apps/v1
metadata:
  name: austin-portfolio
  namespace: personal-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: austin-portfolio
  template:
    metadata:
      labels:
        app: austin-portfolio
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: austin-portfolio
          image: ${CICD_IMAGE}:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: CICD_EXECUTION_SEQUENCE
              value: "${CICD_EXECUTION_SEQUENCE}"

---
kind: Service
apiVersion: v1
metadata:
  name: portfolio-service
  namespace: personal-website
spec:
  type: ClusterIP
  ports:
    - name: portfolio-port
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: austin-portfolio

---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: portfolio-ingress
  namespace: personal-website
spec:
  rules:
    - host: www.austinbspencer.com
      http:
        paths:
          - path: /
            backend:
              serviceName: portfolio-service
              servicePort: portfolio-port
    - host: austinbspencer.com
      http:
        paths:
          - path: /
            backend:
              serviceName: portfolio-service
              servicePort: portfolio-port
